INSERT INTO TIPO_USERS_TABLE (Id_Tipo_Users,Descripcion_user)
VALUES (2,'STUDENT')
INSERT INTO TABLE_SEXO (Id_Sexo,NAME_SEXO)
VALUES (2,'FEMENINO')


INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (1,'ESCA.UST CONTADOR PÚBLICO')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (2,'ESCA.UST LICENCIADO EN RELACIONES COMERCIALES')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (3,'ESCA.UST LICENCIADO EN NEGOCIOS INTERNACIONALES')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (4,'ESCA.UST LICENCIADO EN ADMINISTRACION Y DESARROLLO EMPRESARIA')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (5,'ESCA.UST LICENCIADO EN COMERCIO INTERNACIONAL')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (6,'ESCA.UST LICENCIADO EN COMERCIO INTERNACIONAL (SADE)')
INSERT INTO TABLE_CARRERA (id_carrera,DESCPCION_CARRERARA)
VALUES (7,'ESCA.U.TEP. LICENCIADO EN NEGOCIOS INTERNACIONALES')

INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (1,'ESPERA')
INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (2,'RECHAZADO')
INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (3,'ACEPTADO')
INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (4,'COMPLETADO')
INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (5,'CONCLUIDO')
INSERT INTO STATUS_USER (Id_Estatus_user,DESCRIPICION_STATUS)
VALUES (6,'ARCHIVADO')




