USE master
GO

ALTER DATABASE Sistema_Atencion_SS SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE Sistema_Atencion_SS;
GO

CREATE DATABASE Sistema_Atencion_SS
GO

USE Sistema_Atencion_SS
GO

CREATE TABLE TIPO_USERS_TABLE
(
Id_Tipo_Users INT PRIMARY KEY NOT NULL,
Descripcion_user VARCHAR(20)
)
GO

CREATE TABLE TABLE_SEXO
(
Id_Sexo INT PRIMARY KEY NOT NULL,
NAME_SEXO VARCHAR(15)
);
GO

CREATE TABLE TABLE_CARRERA
(
Id_Carrera INT PRIMARY KEY NOT NULL,
DESCRIPCION_CARRERA VARCHAR(15)
);
GO
ALTER TABLE TABLE_CARRERA
ALTER COLUMN DESCRIPCION_CARRERA VARCHAR(200)
GO

CREATE TABLE STATUS_USER
(
Id_Estatus_user INT PRIMARY KEY NOT NULL,
DESCRIPICION_STATUS VARCHAR(10)
);
GO

CREATE TABLE USERS 
(
Id_user INT PRIMARY KEY NOT NULL IDENTITY,
boleta VARCHAR(25) NOT NULL,
passw VARBINARY(max) NOT NULL,
Tipo_user INT, 
Id_Estatus_user INT,
FOREIGN KEY (Id_Estatus_user) REFERENCES STATUS_USER(Id_Estatus_user),
FOREIGN KEY (Tipo_user) REFERENCES TIPO_USERS_TABLE(Id_Tipo_Users) 
);
GO

CREATE TABLE DATA_USERS
(
Id_data_users INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
user_id INT NOT NULL,
Nombre VARCHAR(40),
A_Paterno VARCHAR(40),
A_Materno VARCHAR(40),
CURP VARCHAR(30),
Boleta VARCHAR(25),
Id_Sexo INT,
Id_Plantel int,
Semestre int, 
CP VARCHAR(30),
Tel_particular VARCHAR(30),
Direccion VARCHAR(max),
Alcaldia VARCHAR(75),
Escolaridad VARCHAR(10),
Correo  VARCHAR(50),
Id_carrera INT,
Clave_carrera VARCHAR (10),
Prestatario VARCHAR(max),
Codigo_Prestatario VARCHAR(30),
Responsable VARCHAR(75),
Programa VARCHAR(max),
Clave_programa VARCHAR(30),
Cargo VARCHAR(75),
Tel_responsable VARCHAR(40),
Fecha_registro date,
Fecha_inicio date,
Fecha_termino date,
Correo_prestatario VARCHAR(50),
Ubicacion_calleynum VARCHAR(75),
Ubicacion_colonia VARCHAR(75),
Ubicacion_alcaldia VARCHAR(75),
Ubicacion_codpos VARCHAR(30),
Token VARCHAR(32),
FOREIGN KEY (Id_carrera) REFERENCES TABLE_CARRERA (Id_Carrera),
FOREIGN KEY (Id_Sexo) REFERENCES TABLE_SEXO (Id_Sexo),
FOREIGN KEY (user_id) REFERENCES USERS (Id_user)
);
GO
CREATE TABLE STATUS_DOCUMETO(
ID_STATUS_DOCUMENTO INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(20)
)
GO
CREATE TABLE TIPO_DOCUMENTO(
ID_TIPO_DOCUMENTO INT PRIMARY KEY NOT NULL,
DESCRIPCION_DOC VARCHAR(40)
)
GO

CREATE TABLE DOCUMENTOS(
NO_REGISTRO VARCHAR(20) PRIMARY KEY,
ID_TIPO_DOCUMENTO INT,
ID_STATUS_DOCUMENTO INT,
FECHA_ENVIO DATE,
FECHA_ACEPTADO DATE,
UBICACION_ARCHIVO VARCHAR(80)
FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
FOREIGN KEY (ID_STATUS_DOCUMENTO) REFERENCES STATUS_DOCUMETO(ID_STATUS_DOCUMENTO)
)
GO
Alter Table DATA_USERS
ADD NO_REGISTRO VARCHAR(20)
GO
Alter Table DATA_USERS
ADD FOREIGN KEY (NO_REGISTRO) REFERENCES DOCUMENTOS(NO_REGISTRO)
GO
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (1,'ACEPTADO')
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (2,'ESPERA APROBACION')
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (3,'RECHAZADO')

INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (1,'EXPEDIENTE')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (2,'EVALUACION DE DESPEÑO')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (3,'CARTA TERMINO')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (4,'CONSTANCIA LIBERACION')



