Use Sistema_Atencion_SS
go
CREATE TABLE STATUS_DOCUMETO(
ID_STATUS_DOCUMENTO INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(20)
)
GO
CREATE TABLE TIPO_DOCUMENTO(
ID_TIPO_DOCUMENTO INT PRIMARY KEY NOT NULL,
DESCRIPCION_DOC VARCHAR(40)
)
GO

CREATE TABLE DOCUMENTOS(
NO_REGISTRO VARCHAR(20) PRIMARY KEY,
ID_TIPO_DOCUMENTO INT,
ID_STATUS_DOCUMENTO INT,
FECHA_ENVIO DATE,
FECHA_ACEPTADO DATE,
UBICACION_ARCHIVO VARCHAR(80)
FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
FOREIGN KEY (ID_STATUS_DOCUMENTO) REFERENCES STATUS_DOCUMETO(ID_STATUS_DOCUMENTO)
)
GO
Alter Table DATA_USERS
ADD NO_REGISTRO VARCHAR(20)
GO
Alter Table DATA_USERS
ADD FOREIGN KEY (NO_REGISTRO) REFERENCES DOCUMENTOS(NO_REGISTRO)
GO
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (1,'ACEPTADO')
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (2,'ESPERA APROBACION')
INSERT INTO STATUS_DOCUMETO (ID_STATUS_DOCUMENTO,DESCRIPCION)
VALUES (3,'RECHAZADO')

INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (1,'EXPEDIENTE')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (2,'EVALUACION DE DESPEÑO')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (3,'CARTA TERMINO')
INSERT INTO TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO,DESCRIPCION_DOC)
VALUES (4,'CONSTANCIA LIBERACION')





