preregistro_mock = [
    {
        "boleta": "2019640295",
        "nombre": "Daniel González Jiménez",
        "carrera": "I. T.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCA UST",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ESPERA",
        "numero": "-",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640296",
        "nombre": "Jorge Angel Cruz Meneses",
        "carrera": "I. T.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "UNIDAD PROFESIONAL INTERDISCIPLINARIA DE INGENIERIA Y TECNOLOGIAS AVANZADAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ESPERA",
        "numero": "-",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640297",
        "nombre": "Joshep Irvin Camacho Dominguez",
        "carrera": "I. T.",
        "semestre": "9",
        "genero": "Femenino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "RECHAZADO",
        "numero": "-",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640298",
        "nombre": "Guillermo Ian Rodriguez Mancera",
        "carrera": "I. T.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ESPERA",
        "numero": "-",
        "registro_lista": "15",
        "f_envio": "01/01/2021",
    },
]

registro_mock = [
    {
        "boleta": "2019640295",
        "nombre": "Daniel González Jiménez",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCA UST",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ACEPTADO",
        "numero": "21140/002",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640296",
        "nombre": "Jorge Angel Cruz Meneses",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "UNIDAD PROFESIONAL INTERDISCIPLINARIA DE INGENIERIA Y TECNOLOGIAS AVANZADAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ACEPTADO",
        "numero": "21140/003",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640297",
        "nombre": "Joshep Irvin Camacho Dominguez",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Femenino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ACEPTADO",
        "numero": "21140/004",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640298",
        "nombre": "Guillermo Ian Rodriguez Mancera",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "ACEPTADO",
        "numero": "21140/005",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
]

completados_mock = [
    {
        "boleta": "2019640295",
        "nombre": "Daniel González Jiménez",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCA UST",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "COMPLETADO",
        "numero": "21140/002",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640296",
        "nombre": "Jorge Angel Cruz Meneses",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "UNIDAD PROFESIONAL INTERDISCIPLINARIA DE INGENIERIA Y TECNOLOGIAS AVANZADAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "COMPLETADO",
        "numero": "21140/003",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640297",
        "nombre": "Joshep Irvin Camacho Dominguez",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Femenino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "COMPLETADO",
        "numero": "21140/004",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
    {
        "boleta": "2019640298",
        "nombre": "Guillermo Ian Rodriguez Mancera",
        "carrera": "I. B.",
        "semestre": "9",
        "genero": "Masculino",
        "prestatario": "ESCUELA SUPERIOR DE COMERCIO Y ADMINISTRACION, UNIDAD SANTO TOMAS",
        "f_inicio": "01/10/2021",
        "f_termino": "01/05/2022",
        "correo_electronico": "dgonzalezj1501@alumno.ipn.mx",
        "estatus": "COMPLETADO",
        "numero": "21140/005",
        "registro_lista": "15",
        "f_envio": "01/01/2021"
    },
]